/*
# Autogenerated floor-based unit numbers

Unit numbers are generated by floor in the format F01-001, F01-002, F02-001.
The advisory lock keeps concurrent admin inserts unique per floor.
*/

CREATE OR REPLACE FUNCTION public.generate_project_unit_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  floor_number text;
  next_sequence integer;
BEGIN
  IF NEW.unit_number IS NULL OR btrim(NEW.unit_number) IN ('', 'AUTO') THEN
    floor_number := regexp_replace(coalesce(NEW.floor, '1'), '[^0-9]', '', 'g');
    IF floor_number = '' THEN floor_number := '1'; END IF;

    PERFORM pg_advisory_xact_lock(hashtext('project_units:' || floor_number));
    SELECT coalesce(max((split_part(unit_number, '-', 2))::integer), 0) + 1
      INTO next_sequence
      FROM public.project_units
     WHERE split_part(unit_number, '-', 1) = 'F' || lpad(floor_number, 2, '0');

    NEW.unit_number := 'F' || lpad(floor_number, 2, '0') || '-' || lpad(next_sequence::text, 3, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS generate_project_unit_number_before_insert ON project_units;
CREATE TRIGGER generate_project_unit_number_before_insert
  BEFORE INSERT ON project_units
  FOR EACH ROW EXECUTE FUNCTION public.generate_project_unit_number();

CREATE UNIQUE INDEX IF NOT EXISTS idx_project_units_unit_number_unique ON project_units (unit_number);
